name: Zipper Continuous Integration

on: [push]

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.build }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        meson_version: ["1.7.2"]
        build: ['debug', 'release']

    env:
      CC: gcc-14
      CXX: g++-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.meson_version }}

      - name: Cache Meson subprojects
        uses: actions/cache@v4
        with:
          path: subprojects/packagecache
          key: subprojects-${{ hashFiles('subprojects/*.wrap') }}

      - name: Install dependencies
        run: bash .github/scripts/dependencies.sh -o linux -m ${{ matrix.meson_version }}

      - name: Configure Project
        run: meson setup . build -Dtesting=true -Dbuildtype=${{ matrix.build }}

      - name: Run Tests
        run: meson test -C build/ -v

      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ubuntu-24.04-${{ matrix.build }}_Meson_Testlog
          path: build/meson-logs/testlog.txt
